version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  api:
    build:
      context: .
    container_name: backend-api
    volumes:
      - ./src:/app/src/
    networks:
      - app-network
    ports:
      - 3333:3333
    command:  bash -c "
      npx prisma generate
      && npx prisma migrate dev --preview-feature
      && npx prisma db seed --preview-feature
      && yarn dev:server"    
    depends_on:
      - rabbitmq
      - db
    restart: on-failure
  db:
    image: postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: 'mydb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5433:5432'
networks:
  app-network:
    driver: bridge
